In [35]:
import torch_geometric as tg
import networkx as nx
import numpy as np
import pandas as pd

from graphgps.loader.dataset.voc_superpixels import VOCSuperpixels


In [2]:
# Given a target node, derive the shortest path to all other nodes

# Then, bucket all other nodes based on this distance.

# Then, assess the accuracy as we modify each bucket

# Repeat for all possible target nodes

In [ ]:
# Load up the dataset

dataset = VOCSuperpixels(root='../datasets/VOCSuperpixels',
                         slic_compactness=30,
                         name='edge_wt_only_coord',
                         split='test')

In [31]:
data = dataset[0].clone()
graph = tg.utils.convert.to_networkx(data)


# Only need to do this once, cache for later
all_shortest_paths = nx.algorithms.shortest_paths.dense.floyd_warshall_numpy(graph).astype(int)

# Identify a target node
target_node_idx = 0

# get the shortest paths to target node
shortest_paths_to_target = all_shortest_paths[:, target_node_idx] # [i, j] is the shortest path from i to j



In [38]:
shortest_paths_df = pd.DataFrame(shortest_paths_to_target)
shortest_paths_df = shortest_paths_df.reset_index().rename(columns = {'index': 'node_id',
                                                         0: 'path_length'})

In [42]:
# Obtain the buckets corresponding to each path length. A map path_length -> node_ids with that path length
path_length_buckets = shortest_paths_df.groupby('path_length')['node_id'].groups

In [45]:
# Now that we have this map, we can use it to create a series of masks for the node values


In [57]:
# First we need to
standard_deviation_of_input = data.x.std(dim=0)
mean_of_input = data.x.mean(dim=0)

mean_of_means = []
for d in dataset:
    graph_mean = d.x.mean(dim=0).numpy()
    mean_of_means.append(graph_mean)
# mean_of_means = np.concatenate(mean_of_means)


# Now fix some path_length and generate a mask for each path length that replaces those node values with a fudged value.

In [58]:
)

[array([3.0865812e-01, 2.4330214e-01, 2.2167920e-01, 1.0834149e-01,
        1.0037090e-01, 9.6856758e-02, 6.9515139e-01, 6.2705129e-01,
        6.0445619e-01, 7.9818852e-02, 4.4632349e-02, 3.7613824e-02,
        2.4425699e+02, 1.8954445e+02], dtype=float32),
 array([4.7993740e-01, 4.7454602e-01, 3.8533941e-01, 2.9506741e-02,
        2.5349451e-02, 2.1287654e-02, 5.7302105e-01, 5.4872268e-01,
        4.4869548e-01, 4.0577903e-01, 4.0597001e-01, 3.2557601e-01,
        1.9926566e+02, 2.4923582e+02], dtype=float32),
 array([6.0925466e-01, 6.4333016e-01, 6.8317008e-01, 6.6913597e-02,
        7.0191041e-02, 7.1239650e-02, 7.6708937e-01, 8.0932492e-01,
        8.5115337e-01, 3.8111138e-01, 4.0729582e-01, 4.4845909e-01,
        1.8634668e+02, 2.4837137e+02], dtype=float32),
 array([4.4287640e-01, 4.2369580e-01, 3.9898065e-01, 4.1774992e-02,
        4.1938830e-02, 4.3507133e-02, 5.8416760e-01, 5.6370980e-01,
        5.4159927e-01, 3.1366348e-01, 2.9420692e-01, 2.6804513e-01,
        1.8842685e+